services:
  db:
    image: mysql:8.0
    container_name: medical_db
    environment:
      - MYSQL_ROOT_PASSWORD=Cipri2005p2005p
      - MYSQL_DATABASE=medical_base_db
    ports:
      - "3307:3306"

  backend:
    image: scpaul16/medical_base_backend:latest
    container_name: medical_base_backend
    environment:
      - PORT_ENV=8000
      - DATABASE_URL=mysql://root:Cipri2005p2005p@db:3306/medical_base_db
    ports:
      - "8080:8000"
    depends_on:
      - db
    command: sh -c "npx prisma db push && node index.js"
    restart: on-failure
  frontend:
    image: scpaul16/medical_base_frontend:latest
    container_name: medical_base_frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
